export const ADD_ROLE_FORM_ACTIONS = {
    OPEN:'OPEN_ADD_ROLE_FORM',
    CLOSE: 'CLOSE_ADD_ROLE_FORM',
    SUBMIT: 'SUBMIT_ADD_ROLE_FORM'
}

export const REGISTRATION_FORM_ACTIONS = {
    SUBMIT: 'SUBMIT_REGISTRATION_FORM'
}