export const HTTPTestData = {
  TARGET: "/test",
  DATA: { test: "DATA" },
  DELETE: "DELETE",
  BACKEND_URL: "BACKEND_URL",
  MY_BACKEND: "http://market.kodekonveyor.com",
  CONFIG_CANT_BE_LOADED: "Config can't be loaded",
  FETCH: "fetch",
  SET_ITEM: "setItem",
  ERROR: "error",
  CONFIG_JSON: "/config.json",
  GET: "GET",
  API_BASE_ROOT: "http://localhost/market",
  JSON_DATA: [{ _id: 1, name: "Janos Ader", role: "Poo with mustache" }],
  GET_ITEM: "getItem",
  POST: "POST",
  PUT: "PUT",
};
